unit Dexed_ttl;

interface

uses Math;

type
  peg_data_t = record
    min,
    max,
    default_value : Single;
    toggled,
    integer,
    logarithmic   : byte;
  end;



  p_port_enum  = (
    p_midi_in                   =   0,
    p_audio_out                 =   1,
    p_cutoff                    =   2,
    p_resonance                 =   3,
    p_output                    =   4,
    p_engine                    =   5,
    p_number_of_voices          =   6,
    p_polymono                  =   7,
    p_pitch_bend_range          =   8,
    p_pitch_bend_step           =   9,
    p_mod_wheel_range           =  10,
    p_mod_wheel_assign          =  11,
    p_foot_ctrl_range           =  12,
    p_foot_ctrl_assign          =  13,
    p_breath_ctrl_range         =  14,
    p_breath_ctrl_assign        =  15,
    p_aftertouch_range          = $10,
    p_aftertouch_assign         =  17,
    p_master_tune               =  18,
    p_algorithm_num             =  19,
    p_feedback                  =  20,
    p_oscillator_sync           =  21,
    p_lfo_speed                 =  22,
    p_lfo_delay                 =  23,
    p_lfo_pitch_mod_depth       =  24,
    p_lfo_amp_mod_depth         =  25,
    p_lfo_sync                  =  26,
    p_lfo_waveform              =  27,
    p_transpose                 =  28,
    p_pitch_mod_sensitivity     =  29,
    p_pitch_eg_rate_1           =  30,
    p_pitch_eg_rate_2           =  31,
    p_pitch_eg_rate_3           = $20,
    p_pitch_eg_rate_4           =  33,
    p_pitch_eg_level_1          =  34,
    p_pitch_eg_level_2          =  35,
    p_pitch_eg_level_3          =  36,
    p_pitch_eg_level_4          =  37,
    p_op1_eg_rate_1             =  38,
    p_op1_eg_rate_2             =  39,
    p_op1_eg_rate_3             =  40,
    p_op1_eg_rate_4             =  41,
    p_op1_eg_level_1            =  42,
    p_op1_eg_level_2            =  43,
    p_op1_eg_level_3            =  44,
    p_op1_eg_level_4            =  45,
    p_op1_operator_output_level =  46,
    p_op1_osc_mode              =  47,
    p_op1_osc_freq_coarse       = $30,
    p_op1_osc_freq_fine         =  49,
    p_op1_osc_detune            =  50,
    p_op1_kbd_lev_scl_brk_pt    =  51,
    p_op1_kbd_lev_scl_lft_depth =  52,
    p_op1_kbd_lev_scl_rht_depth =  53,
    p_op1_kbd_lev_scl_lft_curve =  54,
    p_op1_kbd_lev_scl_rht_curve =  55,
    p_op1_kbd_rate_scaling      =  56,
    p_op1_amp_mod_sensitivity   =  57,
    p_op1_key_vel_sensitivity   =  58,
    p_op2_eg_rate_1             =  59,
    p_op2_eg_rate_2             =  60,
    p_op2_eg_rate_3             =  61,
    p_op2_eg_rate_4             =  62,
    p_op2_eg_level_1            =  63,
    p_op2_eg_level_2            = $40,
    p_op2_eg_level_3            =  65,
    p_op2_eg_level_4            =  66,
    p_op2_operator_output_level =  67,
    p_op2_osc_mode              =  68,
    p_op2_osc_freq_coarse       =  69,
    p_op2_osc_freq_fine         =  70,
    p_op2_osc_detune            =  71,
    p_op2_kbd_lev_scl_brk_pt    =  72,
    p_op2_kbd_lev_scl_lft_depth =  73,
    p_op2_kbd_lev_scl_rht_depth =  74,
    p_op2_kbd_lev_scl_lft_curve =  75,
    p_op2_kbd_lev_scl_rht_curve =  76,
    p_op2_kbd_rate_scaling      =  77,
    p_op2_amp_mod_sensitivity   =  78,
    p_op2_key_vel_sensitivity   =  79,
    p_op3_eg_rate_1             =  80,
    p_op3_eg_rate_2             =  81,
    p_op3_eg_rate_3             =  82,
    p_op3_eg_rate_4             =  83,
    p_op3_eg_level_1            =  84,
    p_op3_eg_level_2            =  85,
    p_op3_eg_level_3            =  86,
    p_op3_eg_level_4            =  87,
    p_op3_operator_output_level =  88,
    p_op3_osc_mode              =  89,
    p_op3_osc_freq_coarse       =  90,
    p_op3_osc_freq_fine         =  91,
    p_op3_osc_detune            =  92,
    p_op3_kbd_lev_scl_brk_pt    =  93,
    p_op3_kbd_lev_scl_lft_depth =  94,
    p_op3_kbd_lev_scl_rht_depth =  95,
    p_op3_kbd_lev_scl_lft_curve = $60,
    p_op3_kbd_lev_scl_rht_curve =  97,
    p_op3_kbd_rate_scaling      =  98,
    p_op3_amp_mod_sensitivity   =  99,
    p_op3_key_vel_sensitivity   = 100,
    p_op4_eg_rate_1             = $65,
    p_op4_eg_rate_2             = $66,
    p_op4_eg_rate_3             = $67,
    p_op4_eg_rate_4             = $68,
    p_op4_eg_level_1            = $69,
    p_op4_eg_level_2            = $6A,
    p_op4_eg_level_3            = $6B,
    p_op4_eg_level_4            = $6C,
    p_op4_operator_output_level = $6D,
    p_op4_osc_mode              = 110,
    p_op4_osc_freq_coarse       = $6F,
    p_op4_osc_freq_fine         = $70,
    p_op4_osc_detune            = $71,
    p_op4_kbd_lev_scl_brk_pt    = $72,
    p_op4_kbd_lev_scl_lft_depth = $73,
    p_op4_kbd_lev_scl_rht_depth = $74,
    p_op4_kbd_lev_scl_lft_curve = $75,
    p_op4_kbd_lev_scl_rht_curve = $76,
    p_op4_kbd_rate_scaling      = $77,
    p_op4_amp_mod_sensitivity   = 120,
    p_op4_key_vel_sensitivity   = $79,
    p_op5_eg_rate_1             = $7A,
    p_op5_eg_rate_2             = $7B,
    p_op5_eg_rate_3             = $7C,
    p_op5_eg_rate_4             = $7D,
    p_op5_eg_level_1            = $7E,
    p_op5_eg_level_2            = $7F,
    p_op5_eg_level_3            = $80,
    p_op5_eg_level_4            = $81,
    p_op5_operator_output_level = 130,
    p_op5_osc_mode              = $83,
    p_op5_osc_freq_coarse       = $84,
    p_op5_osc_freq_fine         = $85,
    p_op5_osc_detune            = $86,
    p_op5_kbd_lev_scl_brk_pt    = $87,
    p_op5_kbd_lev_scl_lft_depth = $88,
    p_op5_kbd_lev_scl_rht_depth = $89,
    p_op5_kbd_lev_scl_lft_curve = $8A,
    p_op5_kbd_lev_scl_rht_curve = $8B,
    p_op5_kbd_rate_scaling      = 140,
    p_op5_amp_mod_sensitivity   = $8D,
    p_op5_key_vel_sensitivity   = $8E,
    p_op6_eg_rate_1             = $8F,
    p_op6_eg_rate_2             = $90,
    p_op6_eg_rate_3             = $91,
    p_op6_eg_rate_4             = $92,
    p_op6_eg_level_1            = $93,
    p_op6_eg_level_2            = $94,
    p_op6_eg_level_3            = $95,
    p_op6_eg_level_4            = 150,
    p_op6_operator_output_level = $97,
    p_op6_osc_mode              = $98,
    p_op6_osc_freq_coarse       = $99,
    p_op6_osc_freq_fine         = $9A,
    p_op6_osc_detune            = $9B,
    p_op6_kbd_lev_scl_brk_pt    = $9C,
    p_op6_kbd_lev_scl_lft_depth = $9D,
    p_op6_kbd_lev_scl_rht_depth = $9E,
    p_op6_kbd_lev_scl_lft_curve = $9F,
    p_op6_kbd_lev_scl_rht_curve = $A0,
    p_op6_kbd_rate_scaling      = $A1,
    p_op6_amp_mod_sensitivity   = $A2,
    p_op6_key_vel_sensitivity   = $A3,
    p_op1_enable                = $A4,
    p_op2_enable                = $A5,
    p_op3_enable                = $A6,
    p_op4_enable                = $A7,
    p_op5_enable                = $A8,
    p_op6_enable                = $A9,
    p_n_ports                   = 170);


var
  _ports : array[p_port_enum] of peg_data_t = (
  ( min:-3.40282e+38; max:3.40282e+38;default_value: -3.40282e+38;toggled: 0;integer: 0;logarithmic: 0 ),
  ( min:-3.40282e+38; max:3.40282e+38; default_value: 3.40282e+38;toggled: 0; integer: 0; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  1; toggled: 0; integer: 0; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  0; toggled: 0; integer: 0; logarithmic: 0 ),
  ( min:  0; max:   2; default_value:  1; toggled: 0; integer: 0; logarithmic: 0 ),
  ( min:  0; max:   2; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  1; max:  32; default_value: 16; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  0; toggled: 1; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  12; default_value:  1; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  12; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 99; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 99; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 99; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 99; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min: -1; max:   1; default_value:  0; toggled: 0; integer: 0; logarithmic: 0 ),
  ( min:  1; max:  32; default_value:  5; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  6; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  0; toggled: 1; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 34; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 33; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  0; toggled: 1; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   5; default_value:  4; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  48; default_value: 24; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  3; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 94; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 67; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 95; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 60; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 50; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 50; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 50; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 50; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 96; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 25; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 25; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 67; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 99; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 75; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 99; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  31; default_value:  1; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min: -7; max:   7; default_value:  3; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  3; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  2; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 95; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 50; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 35; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 78; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 99; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 75; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 58; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  31; default_value: 14; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max: 100; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min: -7; max:   7; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max: 100; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max: 100; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max: 100; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  3; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  7; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 95; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 20; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 20; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 50; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 99; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 95; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 99; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  31; default_value:  1; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min: -7; max:   7; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  3; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  2; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 95; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 29; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 20; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 50; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 99; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 95; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 89; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  31; default_value:  1; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min: -7; max:   7; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  3; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  6; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 95; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 20; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 20; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 50; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 99; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 95; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 99; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  31; default_value:  1; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min: -7; max:   7; default_value: -7; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  3; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 95; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 29; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 20; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 50; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 99; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 95; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 79; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  31; default_value:  1; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min: -7; max:   7; default_value:  7; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 41; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:  99; default_value: 19; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  3; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   3; default_value:  0; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   7; default_value:  6; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  1; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  1; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  1; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  1; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  1; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  1; toggled: 0; integer: 1; logarithmic: 0 ),
  ( min:  0; max:   1; default_value:  1; toggled: 0; integer: 1; logarithmic: 0 )
  );

implementation




end.
